In [1]:
import re,os,time,math,os.path,datetime

#### Python split() 通过指定分隔符对字符串进行切片，如果参数 num 有指定值，则分隔 num+1 个子字符串,返回分割后的字符串列表。

In [2]:
#提取时间戳，
def time_stamp2time(x):
    time_list = [str(i) for i in x.split(' --> ')]
    time_list1_1 = [x for x in time_list[0].split(':')]
    time_list1_2 = [int(x) for x in time_list1_1[2].split(',')]
    time_list1_1.pop()

    time_list2_1 = [x for x in time_list[1].split(':')]
    time_list2_2 = [int(x) for x in time_list2_1[2].split(',')]
    time_list2_1.pop()

    t1=[int(time_list1_1[0]),int(time_list1_1[1]),(time_list1_2[0]+time_list1_2[1]/1000)]
    t2=[int(time_list2_1[0]),int(time_list2_1[1]),(time_list2_2[0]+time_list2_2[1]/1000)]
    return t1,t2

In [9]:
#返回时间戳
def time2time_stamp(x):
    x.append(round((x[2]-math.floor(x[2])),3))
    x[2] = math.floor(x[2])
    H = str(x[0]).zfill(2)
    M = str(x[1]).zfill(2)
    S = str(x[2]).zfill(2)
    MS = str(int(x[3]*1000)).zfill(3)
    time_stamp = H+':'+M+':'+S+','+MS
    return time_stamp

#### Python strip() 方法用于移除字符串头尾指定的字符（默认为空格）或字符序列。                                                                      注意：该方法只能删除开头或是结尾的字符，不能删除中间部分的字符。

#### re.match（）的概念是从头匹配一个符合规则的字符串，从起始位置开始匹配，匹配成功返回一个对象，未匹配成功返回None。

In [123]:
#打开字幕文件，获取字幕的start、end
start = []
end = []
with open(r'C:\Users\renfang\Desktop\text\Temporary1.txt','r',encoding='utf-8') as f1:
#     lines = f1.readlines()
#     for i,line in enumerate(lines):
#         if line=='\n':
#             continue
#         txt.append(line.strip())
        
#     path,name = os.path.split(r'C:\Users\renfang\Desktop\text\Temporary.txt')
#     f2 = open(os.path.join(r'C:\Users\renfang\Desktop\text','Temporary1.txt'),'a')
    for line in f1: 
        if re.match(r'\d{1,2}:\d{1,2}:\d{1,2},\d{1,3} --> \d{1,2}:\d{1,2}:\d{1,2},\d{3}',line):
            line = line.strip()
            time_stamp1 = line

            t1,t2 = time_stamp2time(time_stamp1)
            print(t1,t2)
            t1 = round(t1[0]*3600+t1[1]*60+t1[2]*1,3)
            start.append(t1)
            t2 = round(t2[0]*3600+t2[1]*60+t2[2]*1,3)
            end.append(t2)
print(start,'\n',end)
# #             t1 = modifying_time(t1,s)
# #             t2 = modifying_time(t2,s)

#             time_stamp_1 = time2time_stamp(t1)
#             time_stamp_2 = time2time_stamp(t2)
#             time_stamp2=time_stamp_1+' --> '+time_stamp_2+'\n'
#             line = time_stamp2
#         f2.write(line)
#     f2.close()

[0, 0, 0.39] [0, 0, 3.75]
[0, 0, 4.339] [0, 0, 11.759]
[0, 0, 8.88] [0, 0, 14.929]
[0, 0, 11.759] [0, 0, 18.57]
[0, 0, 14.929] [0, 0, 20.339]
[0, 0, 18.57] [0, 0, 21.899]
[0, 0, 20.339] [0, 0, 24.39]
[0, 0, 21.899] [0, 0, 26.879]
[0, 0, 24.39] [0, 0, 29.01]
[0, 0, 26.879] [0, 0, 33.179]
[0, 0, 29.01] [0, 0, 35.579]
[0, 0, 33.179] [0, 0, 37.619]
[0, 0, 35.579] [0, 0, 40.62]
[0, 0, 37.619] [0, 0, 44.009]
[0, 0, 40.619] [0, 0, 47.009]
[0, 0, 44.009] [0, 0, 48.75]
[0, 0, 47.009] [0, 0, 50.969]
[0, 0, 48.75] [0, 0, 54.57]
[0, 0, 50.969] [0, 0, 56.91]
[0, 0, 54.57] [0, 0, 58.948]
[0, 0, 56.909] [0, 1, 4.289]
[0, 0, 58.948] [0, 1, 6.929]
[0, 1, 4.29] [0, 1, 9.24]
[0, 1, 6.93] [0, 1, 11.97]
[0, 1, 9.239] [0, 1, 14.368]
[0, 1, 11.969] [0, 1, 16.408]
[0, 1, 14.368] [0, 1, 21.45]
[0, 1, 16.409] [0, 1, 24.24]
[0, 1, 21.45] [0, 1, 27.0]
[0, 1, 24.239] [0, 1, 29.158]
[0, 1, 27.0] [0, 1, 32.519]
[0, 1, 29.159] [0, 1, 34.32]
[0, 1, 32.519] [0, 1, 38.64]
[0, 1, 34.319] [0, 1, 40.849]
[0, 1, 38.64] [0, 

#### enumerate() 函数用于将一个可遍历的数据对象(如列表、元组或字符串)组合为一个索引序列，同时列出数据和数据下标，一般用在 for 循环当中。

#### zip() 函数用于将可迭代的对象作为参数，将对象中对应的元素打包成一个个元组，然后返回由这些元组组成的列表。如果各个迭代器的元素个数不一致，则返回列表长度与最短的对象相同，利用 * 号操作符，可以将元组解压为列表

In [124]:
# 获取字幕集的start,end，对应的index
start_time = []
end_time = []
start_ind = []
end_ind = []
start_time.append(start[0])
index = []
ind = 0
index.append(ind)
for i,j in zip(start[1:],end):
    if j >= i:
        ind += 1
        continue
    else:
        index.append(ind)
        end_time.append(j)
        start_time.append(i)
        ind += 1
        index.append(ind)
end_time.append(end[-1])
index.append(ind)
for i in range(0,len(index),2):
    start_ind.append(index[i])
    end_ind.append(index[i+1])

In [125]:
start_time,end_time,index,start_ind,end_ind

([0.39, 4.339], [3.75, 164.198], [0, 0, 1, 55], [0, 1], [0, 55])

In [118]:
# 获取字幕
txt1 = []
txt = []
index = []
with open(r'C:\Users\renfang\Desktop\text\Temporary1.txt','r',encoding='utf-8') as f1:
    lines = f1.readlines()
    for i,line in enumerate(lines):
        if line=='\n':
            continue
        txt.append(line.strip())
for i in range(len(txt)):
    if i%3==0:
        txt1.append(txt[i+2])

In [119]:
# 获取字幕集的单词数
count = []
for i,j in zip(start_ind,end_ind):
    if i == j:
        count1 = 0
        ls = txt1[i].split(" ")
        count1 += len(ls)
        count.append(count1)
    else:
        count2 = 0
        for c in range(i,j+1):
            ls = txt1[c].split(" ")
            count2 += len(ls)
        count.append(count2)

In [120]:
count

[1, 382]

In [121]:
txt1

['[Music]',
 'basic luxury rules I guess you might',
 'consider depending on the type of luxury',
 "that you're doing if you're doing",
 'recreational shooting you want to be',
 "very careful that there's nobody",
 "standing in front of you while you're",
 "shooting or you're not standing in front",
 "of somebody as they're shooting it's a",
 "very simple rule it's common sense",
 'basically obviously a bow is always',
 'considered a weapon or low today we',
 "don't consider it a weapon we consider",
 'it a means of participating in an',
 "athletic sport it's as much of a weapon",
 'as a golf club or a hockey stick but you',
 'know in any other sport there are',
 "dangers and that you've got to be aware",
 'of in archery the dangers are very',
 'apparent because when someone has a bow',
 "and arrow in their hands you're aware of",
 'the danger right away and and you you',
 "act accordingly if you're in an archery",
 "range obviously everybody's standing at",
 "the same line nobody's st

In [152]:
import numpy as np
t = np.zeros((1,2400))
idx = []
for i,start in enumerate(start_time):
    start_i = int(start/0.375)
    end_i = start_i + count[i]
    t[:,start_i:end_i+1] = 1
    idx.append((start_i,end_i))
#     if end_i < int(end_time[i]/0.375):
#         idx[i].append([0]*len(int(end_time[i]/0.375)-end_i))

In [153]:
idx

[(1, 2), (11, 393)]

In [155]:
t.shape

(1, 2400)

### 尝试实现

In [211]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [212]:
# 掩掉当前词的后面所有词
def subsequent_mask(size):
    '''
    in: size               Sc
    out: (1, size, size)   (1,Sc,Sc)
    '''
    mask = torch.ones(1, size, size)
    mask = torch.tril(mask, 0)    # 返回矩阵下三角部分，其余部分定义为0

    return mask.byte()

In [213]:
# 掩掉pad部分和当前词的后面所有词
def mask(src, trg, pad_idx):
    # masking the padding. src shape: (B, Sv) -> (B, 1, Sv)
    src_mask = (src != pad_idx).unsqueeze(1)
    if trg is not None:
        trg_mask = (trg != pad_idx).unsqueeze(-2) & subsequent_mask(trg.size(-1)).type_as(src_mask.data)
        print('trg_mask:\n', trg_mask.shape)
        return src_mask, trg_mask
    else:
        return src_mask

In [214]:
def make_masks(feature_stacks, captions, modality, pad_idx):
    masks = {}

    if modality == 'audio_video_text':
        assert len(feature_stacks['audio'].shape) == 3
        if captions is None:
            masks['A_mask'] = mask(feature_stacks['audio'][:, :, 0], None, pad_idx)
            masks['V_mask'] = mask(feature_stacks['video'][:, :, 0], None, pad_idx)
            masks['T_mask'] = mask(feature_stacks['text'][:, :, 0], None, pad_idx)
        else:
            masks['V_mask'], masks['C_mask'] = mask(feature_stacks['video'][:, :, 0], captions, pad_idx)
            masks['A_mask'] = mask(feature_stacks['audio'][:, :, 0], None, pad_idx)
            masks['T_mask'] = mask(feature_stacks['text'][:, :, 0], None, pad_idx)
    return masks

In [218]:
def attention(Q, K, V, Mask, dropout=None):
    d_k = K.size(-1)
    QKt = Q.matmul(K.transpose(-1,-2))
    att = QKt/np.sqrt(d_k)
    
    if Mask is not None:
        att = att.masked_fill(Mask == 0, -float('inf'))
    
    softmax = F.softmax(att, dim=-1)
    out = softmax.matmul(V)
    
    if dropout is not None:
        out = dropout(out)
        
    return out

In [223]:
class PositionalEncoder(nn.Module):

    def __init__(self, d_model, dout_p, seq_len=3660):
        super(PositionalEncoder, self).__init__()
        self.d_model = d_model
        self.dropout = nn.Dropout(dout_p)

        pos_enc_mat = np.zeros((seq_len, d_model))
        odds = np.arange(0, d_model, 2)
        evens = np.arange(1, d_model, 2)

        for pos in range(seq_len):
            pos_enc_mat[pos, odds] = np.sin(pos / (10000 ** (odds / d_model)))  # 替换pos行，odds列的数据
            pos_enc_mat[pos, evens] = np.cos(pos / (10000 ** (evens / d_model)))

        self.pos_enc_mat = torch.from_numpy(pos_enc_mat).unsqueeze(0)    # (1,3660,d_model)

    def forward(self, x):
        B, S, d_model = x.shape       # (32,S,d_model)
        print('s:\n', S)
        # torch.cuda.FloatTensor torch.FloatTensor
        x = x + self.pos_enc_mat[:, :S, :].type_as(x)    # 位置矩阵与特征矩阵直接相加
        x = self.dropout(x)
        # same as input
        return x       # (32,S,d_model)

In [224]:
feature_stacks = {}
V = torch.randn(1,300,1024)
A = torch.randn(1,800,128)
T = torch.randn(1,2400,300)
V[:,61:,:] = 1
A[:,161:,:] = 1
T[:,:2,:] = 1
T[:,300:,:] = 1
C = torch.randn(1, 35).long()
caption_idx, caption_idx_y = C[:, :-1], C[:, 1:]
feature_stacks['audio'] = A
feature_stacks['video'] = V
feature_stacks['text'] = T

masks = make_masks(feature_stacks, None, 'audio_video_text', 1)
masks1 = torch.cat((masks['V_mask'],masks['A_mask'],masks['T_mask']),-1)
masks1 = masks1.unsqueeze(1)

# 拼接前的纬度变化
linear_v = nn.Linear(1024,1024)
linear_a = nn.Linear(128,1024)
linear_t = nn.Linear(300,1024)
V = linear_v(V)
A = linear_a(A)
T = linear_t(T)

# 拼接
VAT = torch.cat((V,A,T),1)

# 位置编码
pos_enc_vat = PositionalEncoder(1024, 0.1) 
VAT1 = pos_enc_vat(VAT)

# 1、Self-Attention
# 在进行Self-Attention之前的层归一化操作
norm = nn.LayerNorm(1024)
VAT1 = norm(VAT1)

# 多头处理
Q, K, V = VAT1, VAT1, VAT1
Q = Q.view(1, 3500, 4, 256).transpose(-2,-3)
K = K.view(1, 3500, 4, 256).transpose(-2,-3)
V = V.view(1, 3500, 4, 256).transpose(-2,-3)

# 注意力机制
Q_att = attention(Q, K, V, masks1)

# 多头处理
Q_att = Q_att.transpose(-2,-3).contiguous().view(1, 3500, 1024)

# 残差连接???
VAT1 = VAT1 + Q_att

s:
 3500


In [221]:
VAT

tensor([[[ 0.2308, -0.1454,  0.6416,  ..., -0.2255, -0.3067, -0.3917],
         [-0.4189, -0.7420,  0.4821,  ...,  0.2162,  0.0679,  0.9089],
         [ 0.4482, -0.1315,  1.2233,  ..., -0.3031, -0.2870,  0.2325],
         ...,
         [-0.5852,  0.0894,  0.1753,  ...,  0.3825, -0.7355,  0.1522],
         [-0.5852,  0.0894,  0.1753,  ...,  0.3825, -0.7355,  0.1522],
         [-0.5852,  0.0894,  0.1753,  ...,  0.3825, -0.7355,  0.1522]]],
       grad_fn=<CatBackward>)

In [220]:
VAT1

tensor([[[ 0.3393, -0.1863,  0.9205,  ..., -0.2851, -0.3636, -0.5253],
         [-0.5455, -0.9502,  0.6354,  ...,  0.2777,  0.0935,  1.1259],
         [ 0.5794, -0.1190,  1.5232,  ..., -0.3970, -0.3576,  0.2681],
         ...,
         [-0.5807,  0.1264,  0.1660,  ...,  0.4092, -0.7289,  0.0991],
         [-0.5807,  0.1264,  0.1660,  ...,  0.4092, -0.7289,  0.0991],
         [-0.5807,  0.1264,  0.1660,  ...,  0.4092, -0.7289,  0.0991]]],
       grad_fn=<AddBackward0>)

In [205]:
masks

{'A_mask': tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0

In [215]:
masks1

tensor([[[1, 1, 1,  ..., 0, 0, 0]]], dtype=torch.uint8)

In [177]:
vat.shape

torch.Size([1, 3500, 1024])

In [195]:
V

tensor([[[ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
         ...,
         [ 0.7680, -1.8578,  0.7088,  ..., -0.7449,  0.9316,  0.7951],
         [ 0.7866,  0.9117,  1.0180,  ...,  0.2123,  1.6742, -0.2868],
         [-0.1063, -0.7285, -0.5330,  ..., -0.9776,  0.2947, -0.0619]]])

In [ ]:
A

In [190]:
a=torch.randn(1,3,3)
b=torch.randn(1,2,3)
c=torch.randn(1,1,3)
a[:,:2,:]=1
b[:,1:,:]=1
d=torch.cat((a,b,c),1)

In [189]:
a

tensor([[[ 1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000],
         [ 0.7125, -0.0493,  0.2297]]])

In [191]:
d

tensor([[[ 1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000],
         [-0.6533,  0.0042,  0.9642],
         [ 1.7821, -1.0278,  0.2553],
         [ 1.0000,  1.0000,  1.0000],
         [ 0.1070,  1.2576,  0.9142]]])